"""
Dataset: Google Reviews of Restaurants in Majitar, Sikkim
Restaurants:
  1. Imperfecto Restro & Lounge
  2. Punjabi Kitchen
  3. Coffee Break
  4. Down Town Restro & Bar
  5. Baskin Robbins
  6. SK01
  7. KFC
  8. Lapinos
  9. Subway
"""

REVIEWS = [
    # ─────────────────── Imperfecto Restro & Lounge ────────────────────
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 5,
     "review": "Absolutely loved the food and ambiance! The pasta was perfectly cooked and the staff were very friendly. Will definitely come back!"},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 5,
     "review": "One of the best restaurants in Majitar. Great variety on the menu, affordable prices, and the view is stunning."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 4,
     "review": "Really nice place to hang out with friends. The pizza was good, though the service was a bit slow."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 5,
     "review": "Exceptional dining experience! The decor is beautiful and the food quality is outstanding. Highly recommend the momos and noodles."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 3,
     "review": "Decent food but took forever for the order to arrive. The waiter forgot my side dish entirely."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 5,
     "review": "Best restro in the area by far. The Continental dishes are absolutely delightful. The place is very clean too."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 2,
     "review": "Overpriced for what you get. The burger was cold and the cola was flat. Disappointed."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 4,
     "review": "Nice ambiance and good food overall. Could improve on portion sizes but the taste makes up for it."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 5,
     "review": "Perfect spot for a date night! Loved the dim lighting and soothing music. The chicken steak was mouth-watering."},
    {"restaurant": "Imperfecto Restro & Lounge", "rating": 1,
     "review": "Terrible experience. Found a hair in my soup and the staff was extremely rude when I complained. Never going back."},

    # ─────────────────── Punjabi Kitchen ───────────────────────────────
    {"restaurant": "Punjabi Kitchen", "rating": 5,
     "review": "Authentic Punjabi flavors right here in Sikkim! The dal makhani and butter chicken are top-notch. Feels like home."},
    {"restaurant": "Punjabi Kitchen", "rating": 5,
     "review": "Hands down the best North Indian food in Majitar. The naan was soft and the paneer dishes were rich and delicious."},
    {"restaurant": "Punjabi Kitchen", "rating": 4,
     "review": "Very good food at reasonable prices. The lassi is refreshing and the service is prompt. A must-visit!"},
    {"restaurant": "Punjabi Kitchen", "rating": 3,
     "review": "Food is okay, nothing extraordinary. The chole bhature was average compared to what I expected."},
    {"restaurant": "Punjabi Kitchen", "rating": 5,
     "review": "Amazing rajma chawal! The flavors are so authentic. The owner is also very warm and welcoming."},
    {"restaurant": "Punjabi Kitchen", "rating": 4,
     "review": "Great value for money. Large portions, tasty food. The place gets crowded during lunch hours though."},
    {"restaurant": "Punjabi Kitchen", "rating": 2,
     "review": "The food was too oily for my taste and the rice was undercooked. Not a great experience overall."},
    {"restaurant": "Punjabi Kitchen", "rating": 5,
     "review": "Perfectly spiced dishes. The aloo paratha with white butter and pickle is heavenly! Reminded me of my home in Punjab."},
    {"restaurant": "Punjabi Kitchen", "rating": 1,
     "review": "Very unhygienic kitchen. I spotted cockroaches near the counter. This place needs a serious health inspection."},
    {"restaurant": "Punjabi Kitchen", "rating": 4,
     "review": "Loved the thali here. Good spread of dishes. The sweet kheer at the end was the highlight."},

    # ─────────────────── Coffee Break ──────────────────────────────────
    {"restaurant": "Coffee Break", "rating": 5,
     "review": "Best coffee in Majitar hands down! The cappuccino is rich and the brownies are freshly baked. Love this place."},
    {"restaurant": "Coffee Break", "rating": 4,
     "review": "Cozy little cafe near campus. The cold coffee and sandwiches are great. Perfect study spot with free wifi."},
    {"restaurant": "Coffee Break", "rating": 5,
     "review": "Amazing vibes and even better coffee! The staff is super friendly and remembers your usual order. Feels like home."},
    {"restaurant": "Coffee Break", "rating": 3,
     "review": "Coffee is decent but the menu is quite limited. Wish they had more food options beyond snacks."},
    {"restaurant": "Coffee Break", "rating": 5,
     "review": "Perfect hangout for students! Great music, affordable prices, and the hot chocolate is absolutely divine."},
    {"restaurant": "Coffee Break", "rating": 2,
     "review": "Very slow service and the chairs were uncomfortable. The cold coffee tasted watered down. Not worth the wait."},
    {"restaurant": "Coffee Break", "rating": 4,
     "review": "A hidden gem! The lemon iced tea is refreshing and the pastries are always fresh. Great little cafe."},
    {"restaurant": "Coffee Break", "rating": 5,
     "review": "Best hangout spot in Majitar. The staff knows regulars by name. Feels like a home away from home!"},
    {"restaurant": "Coffee Break", "rating": 1,
     "review": "Terrible experience. The coffee was burnt and lukewarm. The cake was stale and overpriced. Total waste of money."},
    {"restaurant": "Coffee Break", "rating": 4,
     "review": "Really enjoyed my evening here. Nice and quiet corner with a good book and a warm latte. Simply lovely."},

    # ─────────────────── Down Town Restro & Bar ─────────────────────────
    {"restaurant": "Down Town Restro & Bar", "rating": 4,
     "review": "Great spot for evening drinks and snacks. The vibe is chill and the music selection is excellent."},
    {"restaurant": "Down Town Restro & Bar", "rating": 5,
     "review": "Love this place! The cocktails are creative and the starters are delicious. Perfect spot for weekend nights."},
    {"restaurant": "Down Town Restro & Bar", "rating": 3,
     "review": "Average experience. The food is okay but nothing special. The bar service is better than the restaurant side."},
    {"restaurant": "Down Town Restro & Bar", "rating": 2,
     "review": "Very loud music made conversation impossible. The food was greasy and overpriced. Won't be returning."},
    {"restaurant": "Down Town Restro & Bar", "rating": 4,
     "review": "Good place for a fun night out. The chicken wings and garlic bread are amazing. Friendly bartenders too."},
    {"restaurant": "Down Town Restro & Bar", "rating": 5,
     "review": "Best bar in Majitar! The ambiance is great and the drinks are strong and well priced. Staff is super friendly."},
    {"restaurant": "Down Town Restro & Bar", "rating": 1,
     "review": "Got food poisoning after eating the fish here. Absolutely terrible. The place needs a hygiene overhaul ASAP."},
    {"restaurant": "Down Town Restro & Bar", "rating": 4,
     "review": "Great food and drinks! The live music on weekends is a bonus. Nice place to unwind after a long day."},
    {"restaurant": "Down Town Restro & Bar", "rating": 3,
     "review": "The food is decent but nothing wow. The service can be slow during peak hours. Drinks are better than the food here."},
    {"restaurant": "Down Town Restro & Bar", "rating": 5,
     "review": "Wonderful place! Had a birthday celebration here and the staff made it very special. Great food and decorations!"},

    # ─────────────────── Baskin Robbins ─────────────────────────────────
    {"restaurant": "Baskin Robbins", "rating": 5,
     "review": "Best ice cream parlour in Majitar! The Mississippi Mud is heavenly and the waffle cones are fresh. Love it!"},
    {"restaurant": "Baskin Robbins", "rating": 4,
     "review": "Good variety of flavours. The sundaes are well made and the staff is friendly. Always a treat to visit."},
    {"restaurant": "Baskin Robbins", "rating": 5,
     "review": "Perfect dessert spot after dinner! The Chocolate Overload shake is incredible. Clean outlet and fast service."},
    {"restaurant": "Baskin Robbins", "rating": 3,
     "review": "Decent ice cream but quite expensive for students. The scoops are small for the price they charge."},
    {"restaurant": "Baskin Robbins", "rating": 5,
     "review": "Amazing flavours every time! The mango sorbet in summer and hot fudge sundae in winter are my favourites."},
    {"restaurant": "Baskin Robbins", "rating": 2,
     "review": "Overpriced and the portions keep getting smaller. The brownie sundae was disappointing this time."},
    {"restaurant": "Baskin Robbins", "rating": 4,
     "review": "Nice place to take a break with friends. The milkshakes are thick and creamy. Good ambiance too."},
    {"restaurant": "Baskin Robbins", "rating": 1,
     "review": "The ice cream cake we ordered for a birthday was melted on arrival. Ruined the celebration. Terrible service."},
    {"restaurant": "Baskin Robbins", "rating": 4,
     "review": "Always consistent quality. The cookies and cream flavour never disappoints. A reliable dessert spot."},
    {"restaurant": "Baskin Robbins", "rating": 3,
     "review": "It is fine for a quick scoop but nothing extraordinary. Same old flavours, wish they introduced more variety."},

    # ─────────────────── SK01 ──────────────────────────────────────────
    {"restaurant": "SK01", "rating": 5,
     "review": "Best place for hangouts in Majitar! The ambiance is fantastic, food is delicious, and the music is great."},
    {"restaurant": "SK01", "rating": 4,
     "review": "Cool vibe and good food. The chicken burger and fries combo is my go-to. Reasonable prices for the quality."},
    {"restaurant": "SK01", "rating": 5,
     "review": "Love this place! The interiors are stylish and the momos are the best I have had in Sikkim. Highly recommend!"},
    {"restaurant": "SK01", "rating": 3,
     "review": "Decent place but gets too noisy on weekends. Food is okay but the service can be slow when crowded."},
    {"restaurant": "SK01", "rating": 5,
     "review": "Amazing experience every time! The pasta and garlic bread are perfectly done. Great spot for date nights."},
    {"restaurant": "SK01", "rating": 2,
     "review": "Very overpriced for what you get. The pizza was soggy and the drinks were weak. Not impressed at all."},
    {"restaurant": "SK01", "rating": 4,
     "review": "Trendy place with a youthful vibe. The nachos and cheese dip are addictive. Good music selection too."},
    {"restaurant": "SK01", "rating": 1,
     "review": "Horrible experience. We waited an hour for food and it was cold when served. Staff was rude and unhelpful."},
    {"restaurant": "SK01", "rating": 4,
     "review": "Nice place for weekend outings. The grilled sandwich is tasty and the shakes are really refreshing."},
    {"restaurant": "SK01", "rating": 5,
     "review": "My favourite spot in Majitar! Everything from the decor to the food to the service is top notch. A must visit."},

    # ─────────────────── KFC ───────────────────────────────────────────
    {"restaurant": "KFC", "rating": 5,
     "review": "Finally KFC in Majitar! The Hot and Crispy chicken is perfectly spiced and crunchy. Just like the big city outlets."},
    {"restaurant": "KFC", "rating": 4,
     "review": "Good fast food option nearby. The Zinger burger is always satisfying and the fries are hot and crispy."},
    {"restaurant": "KFC", "rating": 5,
     "review": "Love the chicken bucket deals! Perfect for sharing with friends after class. Consistent taste every time."},
    {"restaurant": "KFC", "rating": 3,
     "review": "Standard KFC fare. Nothing surprising but nothing bad either. Wish they had more variety in sides."},
    {"restaurant": "KFC", "rating": 4,
     "review": "Quick service and tasty chicken. The Popcorn Chicken is addictive. Clean restaurant and friendly staff."},
    {"restaurant": "KFC", "rating": 2,
     "review": "The chicken was dry and overcooked this time. The coleslaw tasted stale. Not up to the usual KFC standard."},
    {"restaurant": "KFC", "rating": 5,
     "review": "Best fast food in the area hands down! The Chicken Wings are crispy and flavourful. Always a crowd pleaser."},
    {"restaurant": "KFC", "rating": 1,
     "review": "Found a bone splinter in my burger. Extremely dangerous and careless. Filed a complaint immediately."},
    {"restaurant": "KFC", "rating": 4,
     "review": "Reliable and quick. The meal combos are good value and the krushers are a nice refreshing touch."},
    {"restaurant": "KFC", "rating": 3,
     "review": "Decent but repetitive. The menu could use more options. Gets crowded and seating is limited."},

    # ─────────────────── Lapinos ───────────────────────────────────────
    {"restaurant": "Lapinos", "rating": 5,
     "review": "Best pizza in Majitar without any doubt! The cheese burst pizza is loaded and absolutely delicious. Must try!"},
    {"restaurant": "Lapinos", "rating": 4,
     "review": "Great pizza place with good variety. The farmhouse pizza and garlic bread sticks are our favourites."},
    {"restaurant": "Lapinos", "rating": 5,
     "review": "Incredible pizzas at affordable prices! The pepperoni pizza rivals any big brand. Fast delivery too."},
    {"restaurant": "Lapinos", "rating": 3,
     "review": "Pizza is decent but the pasta dishes are average. The crust could be thinner and crispier."},
    {"restaurant": "Lapinos", "rating": 5,
     "review": "Love ordering from Lapinos! The Tandoori Chicken pizza is a unique fusion and tastes amazing every time."},
    {"restaurant": "Lapinos", "rating": 2,
     "review": "The pizza arrived cold and soggy. The delivery took over an hour. Very disappointing experience."},
    {"restaurant": "Lapinos", "rating": 4,
     "review": "Good pizza joint for students. The combo deals are value for money and the dips are tasty."},
    {"restaurant": "Lapinos", "rating": 1,
     "review": "Terrible quality control. The pizza was half raw and the cheese was barely melted. Waste of money."},
    {"restaurant": "Lapinos", "rating": 4,
     "review": "Consistently good pizzas. The Mexican Wave topping is spicy and flavourful. Great weekend treat."},
    {"restaurant": "Lapinos", "rating": 5,
     "review": "Best pizza delivery service around campus! Hot and fresh every time. The paneer tikka pizza is outstanding."},

    # ─────────────────── Subway ────────────────────────────────────────
    {"restaurant": "Subway", "rating": 5,
     "review": "Fresh subs made right in front of you! The Italian BMT with extra veggies is my all-time favourite. So good!"},
    {"restaurant": "Subway", "rating": 4,
     "review": "Healthy and filling option near campus. The Veggie Delight on wheat bread is perfect after a workout."},
    {"restaurant": "Subway", "rating": 5,
     "review": "Love the customization here! The Chicken Teriyaki with honey mustard sauce is absolutely divine."},
    {"restaurant": "Subway", "rating": 3,
     "review": "It is okay. Standard Subway experience. The bread was a bit stale and the veggies did not look fresh."},
    {"restaurant": "Subway", "rating": 4,
     "review": "Good quick meal. The cookies are underrated and the subs are consistently decent. Clean outlet."},
    {"restaurant": "Subway", "rating": 2,
     "review": "Way too expensive for the size of the sub. The Paneer Tikka had barely any filling. Not worth the price."},
    {"restaurant": "Subway", "rating": 5,
     "review": "Best healthy fast food in Majitar! The Tuna sub is fresh and flavourful. Staff is quick and polite."},
    {"restaurant": "Subway", "rating": 1,
     "review": "Disgusting experience. The chicken smelled off and the lettuce was brown. Clearly not fresh ingredients."},
    {"restaurant": "Subway", "rating": 4,
     "review": "Reliable option when you want something light and fresh. The wraps are great and the sauces are tasty."},
    {"restaurant": "Subway", "rating": 3,
     "review": "Average experience. The sub was put together carelessly and fell apart. Service was indifferent."},
]

# ─── FOOD KEYWORDS ─────────────────────────────────────────────────────────────
# Maps a canonical food name → list of search terms (lowercase) to match in reviews.
FOOD_KEYWORDS = {
    "pizza":          ["pizza", "pizzas", "cheese burst", "pepperoni", "farmhouse"],
    "pasta":          ["pasta", "spaghetti", "penne", "macaroni"],
    "momos":          ["momo", "momos"],
    "thukpa":         ["thukpa"],
    "biryani":        ["biryani", "biriyani"],
    "butter chicken": ["butter chicken"],
    "burger":         ["burger", "burgers", "zinger"],
    "chicken":        ["chicken", "popcorn chicken", "chicken bucket",
                       "chicken teriyaki", "tandoori chicken", "fried chicken"],
    "coffee":         ["coffee", "cappuccino", "latte", "espresso", "cold coffee"],
    "tea":            ["tea", "chai", "iced tea", "lemon tea"],
    "sandwich":       ["sandwich", "sandwiches", "sub ", "subs ", "subs.", "wrap", "wraps"],
    "noodles":        ["noodle", "noodles", "chowmein"],
    "ice cream":      ["ice cream", "sundae", "sorbet", "scoop", "waffle cone"],
    "milkshake":      ["milkshake", "milkshakes", "shake", "shakes", "krusher", "krushers"],
    "fries":          ["fries", "french fries"],
    "cake":           ["cake", "cakes"],
    "brownie":        ["brownie", "brownies"],
    "pastries":       ["pastry", "pastries"],
    "paratha":        ["paratha", "parathas", "aloo paratha"],
    "naan":           ["naan", "naans"],
    "dal":            ["dal ", "daal", "dal makhani"],
    "paneer":         ["paneer"],
    "thali":          ["thali"],
    "lassi":          ["lassi"],
    "rajma":          ["rajma"],
    "chole bhature":  ["chole bhature", "chole"],
    "nachos":         ["nachos", "nacho"],
    "garlic bread":   ["garlic bread"],
    "chicken wings":  ["chicken wings", "wings"],
    "cookies":        ["cookie", "cookies"],
    "soup":           ["soup"],
    "steak":          ["steak"],
    "rice":           ["rice", "chawal"],
    "hot chocolate":  ["hot chocolate"],
    "fish":           ["fish", "tuna"],
    "kheer":          ["kheer"],
    "salad":          ["salad"],
    "rolls":          ["roll", "rolls"],
    "dosa":           ["dosa"],
    "idli":           ["idli"],
    "maggi":          ["maggi"],
    "cocktail":       ["cocktail", "cocktails"],
}
